name_car = input("please enter a car name: ")
color_car = input("what's the car's color? ")
year_car = input("when did this car produce? ")
print("This car's name is "+ name_car)
print("The car's color is "+ color_car)
print("The car produced in "+ year_car)